spring:
  application:
    name: recommendation-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password: root
    initialization-mode: always

  sql:
    init:
      mode: always


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
